logging:
  level:
    com:
      kururu:
        simple:
          project: DEBUG
    org:
      springframework: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: parkingArea1!
    url: jdbc:mysql://localhost:3306/parkingArea?serverTimezone=UTC&characterEncoding=UTF-8
    username: parkingArea
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MySQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
  main:
    web-application-type: NONE
