CREATE TABLE IF NOT EXISTS LOT_INFORMATION
(
    LOT_NUMBER        integer      NOT NULL AUTO_INCREMENT,
    LOT_NAME          varchar(100) NOT NULL,
    ACCEPTABLE_SMALL  int(100)     NOT NULL,
    ACCEPTABLE_MEDIUM int(100)     NOT NULL,
    ACCEPTABLE_HEAVY  int(100)     NOT NULL,
    DEL_FLG           CHAR(1)      NOT NULL,
    PRIMARY KEY (LOT_NUMBER)
);

CREATE TABLE IF NOT EXISTS ENTRY_BOOK
(
    VEHICLE_NUMBER   varchar(20) NOT NULL,
    CLIENT_NUMBER    varchar(10) NOT NULL DEFAULT 'Non-Member',
    ARRIVAL_TIME     timestamp   NOT NULL,
    DEPARTURE_TIME   timestamp   NULL,
    HOURS_OF_USE     int(2)      NULL,
    COST_OF_USE      int(2)      NULL,
    END_BUSINESS_FLG char(1)     NOT NULL DEFAULT '0',
    PRIMARY KEY (VEHICLE_NUMBER)
);